Update publish-build.yml

diff --git a/.github/workflows/publish-build.yml b/.github/workflows/publish-build.yml
--- a/.github/workflows/publish-build.yml
+++ b/.github/workflows/publish-build.yml
@@ -129,14 +129,18 @@ jobs:
           version: 'latest'
           
       - name: Set up kubectl
+        env:
+          KUBECONFIG: ~/.kube/config
         run: |
           # Get the kubeconfig for your EKS cluster
           # kubectl version
           aws eks update-kubeconfig --name retail-store-eks --region us-east-1
           echo "Verifying kubeconfig setup..."
-          cat ~/.kube/config  # This helps verify if kubeconfig was created
-          kubectl get nodes  # Test command to verify connection to EKS cluster
+          cat ~/.kube/config  # This helps verify if kubeconfig was created          
           kubectl version
+          echo "Current kubectl context:"
+          kubectl config current-context
+          kubectl get nodes || echo "Error: Unable to connect to the EKS cluster"
 
       - name: Deploy to EKS
         env:
